accounts/urls.py
from django.urls import path

from . import views

app_name = 'auth'

urlpatterns = [
    path('login/', views.loginView, name='login'),
    path('register/', views.registerView, name='register'),
    path('logout/', views.logoutView, name='logout'),
    path('settings/', views.SettingsView, name='settings'),
    path('profil/', views.ProfilView, name='profil'),

    path('fav_tags/update/', views.UpdateFavTags, name='update_tags')
]

blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),

    path('user_profil/<id>/', views.userProfilView, name='user_profil'),

    path('articles/<uuid:id>/', views.articleView, name='article_details'),
    path('articles/<uuid:id>/delete/', views.deleteArticleView, name='delete_article'),
    path('articles/<uuid:id>/edit/', views.updateArticleView, name='update_article'),
    path('articles/new/', views.createArticleView, name='new_article'),

    path('search/', views.searchView, name='search'),

    path('articles/<uuid:id>/clap/', views.addClap, name='add_clap'),
    path('articles/<uuid:id>/clap/delete', views.deleteClap, name='delete_clap'),
]

medium_clone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('auth/', include('accounts.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User

import uuid

class Tag(models.Model) :
    name = models.CharField(max_length=200)

    def __str__(self) :
        return self.name

class Article(models.Model) :
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    title = models.CharField(max_length=200)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)
    overview = models.TextField(max_length=5000)
    content = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    views = models.IntegerField(default=0)

    class Meta :
        constraints = [
            models.UniqueConstraint(fields=['title', 'author'], name='non_duplicated_titles'),
            models.UniqueConstraint(fields=['content'], name='unique_article_content')
        ]

    def __str__(self) :
        return f'{self.title} by {self.author.username}'

    def get_tags(self) :
        return ' '.join(['#' + tag.name.replace(' ', '_') for tag in self.tags.all()])

    get_tags.short_description = 'Tags'

class Clap(models.Model) :
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta :
        constraints = [
            models.UniqueConstraint(fields=['user', 'article'], name='unique_clap_user_article')
        ]

blog/forms.py
from django import forms

from .models import Article

class CreateArticleForm(forms.ModelForm) :
    class Meta :
        model = Article
        fields = '__all__'
        exclude = ['id', 'author', 'views']

blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.urls import reverse
from django.db.models import Q

from .forms import CreateArticleForm

from markdown2 import Markdown
from .models import Article, Tag, Clap

import json

def index(request) :
    articles = Article.objects.all().order_by('-date_created')
    trends = articles.order_by('-views')
    try :
        fav_tags_ids = [tag.id for tag in request.user.profil.fav_tags.all()]
        recomended = list()

        for article in articles :
            tags = [tag.id for tag in article.tags.all()]
            for fav in fav_tags_ids :
                if fav in tags :
                    recomended.append(article)
                    break
        
        context = { 'recomended': recomended[:4], 'latest': articles[:4], 'trends': trends[:4] }
    except :
        context = { 'recomended': None, 'latest': articles[:4], 'trends': trends }

    return render(request, 'blog/index.html', context)

@login_required(login_url='auth:login')
def userProfilView(request, id) :
    try :
        user = User.objects.get(pk=id)
    except :
        raise Http404()

    articles = user.article_set.all().order_by('-date_created')

    return render(request, 'blog/profil.html', { 'user': user, 'articles': articles })

def articleView(request, id) :
    try :
        article = Article.objects.get(pk=id)
    except :
        raise Http404()

    try :
        user_clap = Clap.objects.get(user=request.user, article=article)
    except :
        user_clap = None

    article.views += 1
    article.save()

    markdowner = Markdown(extras=['fenced-code-blocks'])
    content = markdowner.convert(article.content)
    claps_count = article.clap_set.all().count()

    tags = article.tags.all()
    features = Article.objects.filter(tags__in=tags).exclude(id=str(article.id)).order_by('-views')
    articles = Article.objects.all().order_by('-date_created')

    context = { 
        'article': article, 
        'content': content, 
        'claps_count': claps_count, 
        'user_clap': user_clap, 
        'features': features[0:3],
        'latest': articles[0:3]
    }
    return render(request, 'blog/article.html', context)

@login_required(login_url='auth:login')
def createArticleView(request) :
    if request.method == 'GET' :
        form = CreateArticleForm()
        context = { 'form' : form, 'title': 'Create New Article', 'btn': 'create' }
        return render(request, 'blog/create_article.html', context)

    if request.method == 'POST' :
        user = request.user
        form = CreateArticleForm(request.POST)

        if form.is_valid() :
            d = {**request.POST}
            article = form.save(commit=False)
            article.author = user
            article.save()

            for tag_id in d.get('tags') :
                tag = Tag.objects.get(pk=tag_id)
                article.tags.add(tag)

            return redirect(reverse('blog:article_details', args=[str(article.id)]))

        else :
            for error in form.errors :
                messages.error(request, form.errors.get(error)[0])

            context = { 'form' : form, 'title': 'Create New Article', 'btn': 'create' }
            return render(request, 'blog/create_article.html', context)

@login_required(login_url='auth:login')
def updateArticleView(request, id) :
    try :
        article = Article.objects.get(pk=id)
    except :
        raise Http404()

    if request.user != article.author and not request.user.is_staff :
        return HttpResponse('You not allowed')
    
    elif request.method == 'GET' :
        form = CreateArticleForm(instance=article)
        context = { 'form' : form, 'title': 'Update Article', 'btn': 'save' }
        return render(request, 'blog/create_article.html', context)

    elif request.method == 'POST' :
        form = CreateArticleForm(request.POST, instance=article)

        if form.is_valid() :
            article = form.save()
            return redirect(reverse('blog:article_details', args=[str(article.id)]))
        else :
            for error in form.errors :
                messages.error(request, form.errors.get(error)[0])

            context = { 'form' : form, 'title': 'Update Article', 'btn': 'save' }
            return render(request, 'blog/create_article.html', context)

@login_required(login_url='auth:login')
def deleteArticleView(request, id) :
    try :
        article = Article.objects.get(pk=id)
    except :
        raise Http404()

    if article.author != request.user and not request.user.is_staff :
        return HttpResponse('You are not allowed')

    elif request.method == 'GET' :
        return render(request, 'blog/delete_article.html', { 'article': article })

    elif request.method == 'POST' :
        article.delete()
        return redirect(reverse('blog:index'))

@login_required(login_url='auth:login')
def addClap(request, id) :
    try :
        article = Article.objects.get(pk=id)
    except :
        raise Http404()

    user = request.user 
    clap = Clap.objects.create(article=article, user=user)

    return HttpResponse(json.dumps({'status': 201, 'message': 'clap created'}), status=201)

@login_required(login_url='auth:login')
def deleteClap(request, id) :
    try :
        article = Article.objects.get(pk=id)
        user = request.user
        clap = Clap.objects.get(article=article, user=user)
        clap.delete()
    except :
        raise Http404()

    return HttpResponse(json.dumps({'status': 201, 'message': 'clap deleted'}), status=201)

def searchView(request) :
    query = request.GET.get('q')

    if query != '' :
        users = User.objects.filter(
            Q(first_name__startswith=query) | 
            Q(last_name__startswith=query) | 
            Q(username__startswith=query)
        )

        articles = Article.objects.filter(
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(overview__icontains=query)
        )
    else :
        users = []
        articles = []

    context = { 'query': query, 'users': users, 'articles': articles }
    return render(request, 'blog/search.html', context)

blog/templates/blog/article.html
{% extends 'blog/base.html' %}

{% load static %}
{% block content %}
<style>
    img {
        max-width: 100%;
        display: block;
    }
</style>
<link rel="stylesheet" href="{% static 'css/code.css' %}" >
<div class="container mt-2 mb-5">
    <!-- Start Model -->
    <div class="modal fade" id="model" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLongTitle">Login Required</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              You must be logged in to like this article. 
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <a href="{% url 'auth:login' %}?next={{ request.path }}" class="btn btn-primary">Login</a>
            </div>
          </div>
        </div>
    </div>
    <!-- End Model -->
    <div class="row">
        <div class="col-7">
            <div class="card card-body my-3">
                <h3 class="card-title">{{ article.title }}</h3>
                <a href="{% url 'blog:user_profil' article.author.id %} " class="m-0">
                    {% if article.author.first_name and article.author.last_name %}
                    {{ article.author.first_name }} {{ article.author.last_name }}
                    {% else %} 
                    {{ article.author.username }}
                    {% endif %} 
                </a>
                <small>{{ article.date_updated|date:"M d, Y"}}</small>

                {% if request.user == article.author %}
                <p class="my-1">{{ article.clap_set.all.count }} claps </p>
                <p class="my-1">{{ article.views }} views </p>
                <div class="my-3">
                    <a href="{% url 'blog:update_article' article.id %} " class="btn btn-info">Update</a>
                    <a href="{% url 'blog:delete_article' article.id %} " class="btn btn-danger">Delete</a>
                </div>
                {% endif %}
            </div>

            <div>
                {{content|safe}}
            </div>

            <div class="card card-body">
                <strong>{{ article.get_tags }}</strong>
                <span><span id="claps_count">{{ claps_count }} </span> likes </span>
                <div class="mt-3">
                    {% if user_clap %}
                    <button class="btn btn-warning" id="clap" data-id="{{ article.id }}" data-liked="true">Unlike</button> 
                    {% else %}
                    <button class="btn btn-primary" id="clap" data-id="{{ article.id }}">Like</button> 
                    {% endif %}
                </div>
                <button style="display: none;" type="button" class="btn btn-primary" data-toggle="modal" data-target="#model" id="btn-model">
                    Launch demo modal
                </button>
            </div>
        </div>
        <div class="col-5 my-3">
            <div class="card">
                {% if features|length > 0 %}
                <div class="card-header">
                    <h5 class="card-title">Features</h5>
                </div>
                <div class="card-body">
                    {% for article in features %}
                    <div class="row">
                        <div class="col-12">
                            <h6>{{ article.title }}</h6>
                            <small>{{ article.date_updated }} </small>
                            <p>by <a href="{% url 'blog:user_profil' article.author.id %}">@{{ article.author }}</a> </p>
                            <p>{{ article.overview }}</p>
                            <a href="{% url 'blog:article_details' article.id %}" class="btn btn-info btn-block text-white">View Article</a>
                        </div>
                    </div>
                    <hr/>
                    {% endfor %}
                </div>
                {% else %}
                <div class="card-header">
                    <h5 class="card-title">Latest Articles</h5>
                </div>
                <div class="card-body">
                    {% for article in latest %}
                    <div class="row">
                        <div class="col-12">
                            <h6>{{ article.title }}</h6>
                            <small>{{ article.date_updated }} </small>
                            <p>by <a href="{% url 'blog:user_profil' article.author.id %}">@{{ article.author }}</a> </p>
                            <p>{{ article.overview }}</p>
                            <a href="{% url 'blog:article_details' article.id %}" class="btn btn-info btn-block text-white">View Article</a>
                        </div>
                    </div>
                    <hr/>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block script %}
<script src="{% static 'js/claps.js' %}"></script>
{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}<title>Ugly Face</title>{% endblock %}

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
    {% include 'blog/navbar.html' %}

    
    {% block content %}{% endblock %}
    
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    {% block script %}{% endblock %}
</body>
</html>

blog/templates/blog/create_article.html
{% extends 'blog/base.html' %}

{% load static %}
{% block content %}
<div class="container my-5">
    <div class="row">
        <div class="col">
            <div class="card card-body">
                <h4 class="card-title">{{ title }}</h4>
                <form method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">
                        <label>{{field.label}}*</label>
                        {{ field }}
                    </div>
                    {% endfor %}

                    {% if messages %}
                    {% for msg in messages %}
                    {% if msg.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    <div class="alert alert-danger">{{ msg }}</div>
                    {% endif %}
                    {% endfor %}
                    {% endif %}

                    <input type="submit" class="btn btn-primary btn-block" value="{{btn}}" />
                </form>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'js/forms.js' %}"></script>
{% endblock %}

blog/templates/blog/delete_article.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto my-5">
            <div class="card card-body">
                <h5 class="card-title">Delete Article</h5>
                <form method="POST">
                    {% csrf_token %}
                    <p>Do you realy wan to delete article "<strong>{{ article.title|upper }}</strong>".</p>
                    <input type="submit" value="Confirm" class="btn btn-warning">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
<div class="index__hero">
    <h3 class="hero__title">Welcome To The World Of The Knowlege.</h3>
    <p class="hero__subtitle">The only way to get smarter.</p>
</div>

<div class="container my-3">
    {% if recomended %}
    <h2 class="text-center mb-5 display-4">Recommandations</h2>
    <div class="row justify-content-center mb-5">
        {% for article in recomended %}
        <div class="col-lg-8 col-12 my-2">
            <div class="card card-body bg-dark">
                <div class="media text-white">
                    <img src="/media/{{ article.author.profil.profil_pic }}" class="mr-3 profil_pic" alt="author profil">
                    <div class="media-body">
                        <h5 class="mt-0">{{ article.title }}</h5>
                        <p class="m-0">by <a href="{% url 'blog:user_profil' article.author.id %} ">@{{ article.author }} </a></p>
                        <small>{{ article.date_updated }}</small>
                        <p class="my-3">{{ article.overview }}</p>
                        <p class="my-3"><strong>{{ article.get_tags }}</strong>  </p>
                        <div>
                            <a href="{% url 'blog:article_details' article.id %}" class="btn btn-primary">View</a>
                            {% if request.user == article.author %}
                            <a href="{% url 'blog:update_article' article.id %} " class="btn btn-info">Update</a>
                            <a href="{% url 'blog:delete_article' article.id %} " class="btn btn-danger">Delete</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <hr>
    {% endif %}
    
    <h2 class="text-center mb-5 display-4">Trending</h2>
    <div class="row justify-content-center mb-5">
        {% for article in trends %}
        <div class="col-lg-8 col-12 my-2">
            <div class="card card-body bg-dark">
                <div class="media text-white">
                    <img src="/media/{{ article.author.profil.profil_pic }}" class="mr-3 profil_pic" alt="author profil">
                    <div class="media-body">
                        <h5 class="mt-0">{{ article.title }}</h5>
                        <p class="m-0">by <a href="{% url 'blog:user_profil' article.author.id %} ">@{{ article.author }} </a></p>
                        <small>{{ article.date_updated }}</small>
                        <p class="my-3">{{ article.overview }}</p>
                        <p class="my-3"><strong>{{ article.get_tags }}</strong>  </p>
                        <div>
                            <a href="{% url 'blog:article_details' article.id %}" class="btn btn-primary">View</a>
                            {% if request.user == article.author %}
                            <a href="{% url 'blog:update_article' article.id %} " class="btn btn-info">Update</a>
                            <a href="{% url 'blog:delete_article' article.id %} " class="btn btn-danger">Delete</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <hr>

    <h2 class="text-center mb-5 display-4">Latest Articles</h2>
    <div class="row justify-content-center mb-5">
        {% for article in latest %}
        <div class="col-lg-8 col-12 my-2">
            <div class="card card-body bg-dark">
                <div class="media text-white">
                    <img src="/media/{{ article.author.profil.profil_pic }}" class="mr-3 profil_pic" alt="author profil">
                    <div class="media-body">
                        <h5 class="mt-0">{{ article.title }}</h5>
                        <p class="m-0">by <a href="{% url 'blog:user_profil' article.author.id %} ">@{{ article.author }} </a></p>
                        <small>{{ article.date_updated }}</small>
                        <p class="my-3">{{ article.overview }}</p>
                        <p class="my-3"><strong>{{ article.get_tags }}</strong>  </p>
                        <div>
                            <a href="{% url 'blog:article_details' article.id %}" class="btn btn-primary">View</a>
                            {% if request.user == article.author %}
                            <a href="{% url 'blog:update_article' article.id %} " class="btn btn-info">Update</a>
                            <a href="{% url 'blog:delete_article' article.id %} " class="btn btn-danger">Delete</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

blog/templates/blog/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'blog:index' %}">Ugly Face Blog</a>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auth:profil' %}">Profil</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:new_article' %}">New Article</a>
            </li>
            {% endif %}
        </ul>
        <form action="{% url 'blog:search' %}" class="form-inline my-2 my-lg-0 mx-lg-4">
            <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-info my-2 my-sm-0" type="submit">Search</button>
        </form>

        <ul class="navbar-nav">
            {% if request.user.is_authenticated %}
            <li class="nav-item mb-3 mb-lg-0">
                <a class="btn-secondary btn btn-block" href="{% url 'auth:logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item mb-3 mb-lg-0">
                <a class="nav-link" href="{% url 'auth:login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auth:register' %}">Register</a>
            </li>
            {% endif %}
        </ul>
    </div>
    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
</nav>

blog/templates/blog/profil.html
{% extends 'blog/base.html' %}

{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/profil.css' %}">
<div class="container my-5">
    <div class="row my-2">
        <div class="col">
            <div class="card card-body">
                <div class="row">
                    <div class="col-md-3">
                        <img class="img-fluid profil_pic" src="/media/{{ user.profil.profil_pic }}" /> 
                    </div>
                    <div class="col">
                        <h3 class="display-4">
                            {% if user.last_name and user.first_name %}
                            {{ user.last_name }} {{ user.first_name  }}
                            {% else %}
                            {{ user.username }}
                            {% endif %}
                        </h3>
                        <p><strong>@{{ user.username }}</strong></p>
                        <p>{{ user.article_set.all.count }} articles </p>
                        {% if user == request.user %}
                        <a href="{% url 'auth:settings' %}" class="btn btn-secondary">Settings</a>
                        <a href="{% url 'blog:new_article' %}" class="btn btn-info">New Article</a>
                        {% endif %}
                    </div>
                </div>
                
            </div>
        </div>
    </div>
</div>
{% if articles|length > 0%}
<div class="container">
    <h4>ARTICLES</h4>
    <hr>
    {% for article in articles %}
    <div class="row my-3">
        <div class="col-md-7">
            <div class="card card-body">
                <h5 class="mt-0">{{ article.title }}</h5>
                <small>{{ article.date_updated }}</small>
                <p class="my-3">{{ article.overview }}</p>
                <p class="my-3"><strong>{{ article.get_tags }}</strong>  </p>
                <div>
                    <a href="{% url 'blog:article_details' article.id %}" class="btn btn-primary">View</a>
                    {% if request.user == article.author %}
                    <a href="#" class="btn btn-info">Update</a>
                    <a href="{% url 'blog:delete_article' article.id %} " class="btn btn-danger">Delete</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
<div class="container">
    <div class="row">
        <div class="col-12 alert alert-secondary alert-v">No articles in this profil.</div>
    </div>
</div>
{% endif %}
{% endblock %}

blog/templates/blog/search.html
{% extends 'blog/base.html' %}

{% load static %}
{% block content %}
<style>
    .profil_pic {
        object-fit: cover;
        width: 80px;
        height: 80px;
        border-radius: 50%;
    }
</style>
<div class="container py-5">
    <h4 class="display-3">Search for "{{ query }}" :</h4>
    {% if user|length == 0 and articles|length == 0 %}
    <hr>
    <div class="row">
        <div class="col-12 alert alert-secondary">
            <p class="text-center h2">No Results For '{{ query }}'</p>    
        </div>
        <a href="{% url 'blog:index' %}" class="btn btn-warning btn-block">Go Back home</a>  
    </div>
    
    {% endif %}

    {% if users|length > 0 %}
    <hr>
    <h5 class="display-4">Authors :</h5>
    <div class="row">
        {% for user in users %}
        <div class="col-3">
            <div class="card">
                <img src="/media/{{ user.profil.profil_pic }}/" class="img-fluid" />
                <div class="card-body">
                    <h5 class="card-title">@{{ user.username }}</h5>
                    <p>{{ user.first_name }} {{ user.last_name }}</p>
                    <p>{{ user.article_set.all.count }} articles</p>
                    <a href="{% url 'blog:user_profil' user.id %}" class="btn btn-info">View Profil</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endif %}

    {% if articles|length > 0 %}
    <hr>
    <h5 class="display-4">Articles :</h5>
    {% for article in articles %}
    <div class="row mb-5">
    <div class="col-8">
        <div class="card card-body bg-dark">
            <div class="media text-white">
                <img src="/media/{{ article.author.profil.profil_pic }}" class="mr-3 profil_pic" alt="author profil">
                <div class="media-body">
                    <h5 class="mt-0">{{ article.title }}</h5>
                    <p class="m-0">by @<a href="{% url 'blog:user_profil' article.author.id %} ">{{ article.author }} </a></p>
                    <small>{{ article.date_updated }}</small>
                    <p class="my-3">{{ article.overview }}</p>
                    <p class="my-3"><strong>{{ article.get_tags }}</strong>  </p>
                    <div>
                        <a href="{% url 'blog:article_details' article.id %}" class="btn btn-primary">View</a>
                        {% if request.user == article.author %}
                        <a href="{% url 'blog:update_article' article.id %} " class="btn btn-info">Update</a>
                        <a href="{% url 'blog:delete_article' article.id %} " class="btn btn-danger">Delete</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    {% endfor %}
    {% endif %}
</div>
{% endblock %}